### PR TITLE
Added full paths to fix build script issues

### PR DESCRIPTION
**Pull request by S0ulf3re**
I added the full homebrew paths to try to help fix the build issues

### CODE REVIEW

**Comment by ggoraa** [comment]
Thanks for the pull request!
I ran the project on my local machine, and I got this:
```
<thruncated>.sh: line 5: /opt/homebrew/bin/gyb: No such file or directory
<thruncated>.sh: line 5: /opt/homebrew/bin/gyb: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code
```
I think you are trying to fix this, but my suspicions are that these fixes only apply to your local environment, and do not apply to everyone else.
By further investigating I see that you have an Apple Silicon mac, because Homebrew installs software to /opt/homebrew/bin only when it is an ARM Mac. Can you place `where gyb`, `where swiftlint` in each respective build phase? It should output the path to that software in the build log (you can see it by pressing ⌘+9 and clicking on the first item)

**Comment by S0ulf3re** [comment]
> Hi, and thanks for the pull request! I ran the project on my local machine, and I got this:
> 
> ```
> <thruncated>.sh: line 5: /opt/homebrew/bin/gyb: No such file or directory
> Command PhaseScriptExecution failed with a nonzero exit code
> ```
> 
> I think you are trying to fix this, but my suspicions are that these fixes only apply to your local environment, and do not apply to everyone else. By further investigating I see that you have an Apple Silicon mac, because Homebrew installs software to /opt/homebrew/bin only when it is an ARM Mac. Can you place `where gyb`, `where swiftlint` in each respective build phase? It should output the path to that software in the build log (you can see it by pressing ⌘+9 and clicking on the first item, it will open the full log in the editor)

I can confirm I do own an M1 MacBook. And I just used where and indeed, both are appearing in /opt/homebrew/bin/.

**Comment by ggoraa** [comment]
Did you confirm that gyb and swiftlint are there by looking at the build log, or by running these commands in the terminal?

**Comment by S0ulf3re** [comment]
`❯ where gyb`
`/opt/homebrew/bin/gyb`
`❯ where swiftlint`
`/opt/homebrew/bin/swiftlint`

**Comment by ggoraa** [comment]
Wait, I have an idea
Can you clean:
```
~/Library/Caches
~/Library/Developer/Xcode/DerivedData
```
And try to build without the absolute path to gyb and swiftlint?

**Pull request closed without merging**
